config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :bookmarks

      resources :image_comments

      resources :upload_images

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "upload_images#index"
  resources :bookmarks
  resources :image_comments
  resources :upload_images
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/upload_image.rb
class UploadImage < ApplicationRecord
  mount_uploader :image, ImageUploader

  enum vibe: { "casual" => 0, "evening_wear" => 1, "professional" => 2 }

  # Direct associations

  has_many   :bookmarks,
             foreign_key: "image_id",
             dependent: :destroy

  has_many   :image_comments,
             foreign_key: "image_id",
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    created_at
  end
end

app/controllers/api/v1/upload_images_controller.rb
class Api::V1::UploadImagesController < Api::V1::GraphitiController
  def index
    upload_images = UploadImageResource.all(params)
    respond_with(upload_images)
  end

  def show
    upload_image = UploadImageResource.find(params)
    respond_with(upload_image)
  end

  def create
    upload_image = UploadImageResource.build(params)

    if upload_image.save
      render jsonapi: upload_image, status: :created
    else
      render jsonapi_errors: upload_image
    end
  end

  def update
    upload_image = UploadImageResource.find(params)

    if upload_image.update_attributes
      render jsonapi: upload_image
    else
      render jsonapi_errors: upload_image
    end
  end

  def destroy
    upload_image = UploadImageResource.find(params)

    if upload_image.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: upload_image
    end
  end
end

app/controllers/upload_images_controller.rb
class UploadImagesController < ApplicationController
  before_action :set_upload_image, only: %i[show edit update destroy]

  def index
    @q = UploadImage.ransack(params[:q])
    @upload_images = @q.result(distinct: true).includes(:image_comments,
                                                        :bookmarks).page(params[:page]).per(10)
  end

  def show
    @bookmark = Bookmark.new
    @image_comment = ImageComment.new
  end

  def new
    @upload_image = UploadImage.new
  end

  def edit; end

  def create
    @upload_image = UploadImage.new(upload_image_params)

    if @upload_image.save
      redirect_to @upload_image,
                  notice: "Upload image was successfully created."
    else
      render :new
    end
  end

  def update
    if @upload_image.update(upload_image_params)
      redirect_to @upload_image,
                  notice: "Upload image was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @upload_image.destroy
    redirect_to upload_images_url,
                notice: "Upload image was successfully destroyed."
  end

  private

  def set_upload_image
    @upload_image = UploadImage.find(params[:id])
  end

  def upload_image_params
    params.require(:upload_image).permit(:image, :topstyle, :topcolor,
                                         :bottomstyle, :bottomcolor, :shoestyle, :shoecolor, :vibe)
  end
end

app/views/upload_images/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Upload Image #<%= upload_image.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Image</dt>
      <dd>
        <%= cl_image_tag @upload_image.image, class: "img-fluid" %>
      </dd>

      <dt>Topstyle</dt>
      <dd><%= upload_image.topstyle %></dd>

      <dt>Topcolor</dt>
      <dd><%= upload_image.topcolor %></dd>

      <dt>Bottomstyle</dt>
      <dd><%= upload_image.bottomstyle %></dd>

      <dt>Bottomcolor</dt>
      <dd><%= upload_image.bottomcolor %></dd>

      <dt>Shoestyle</dt>
      <dd><%= upload_image.shoestyle %></dd>

      <dt>Shoecolor</dt>
      <dd><%= upload_image.shoecolor %></dd>

      <dt>Vibe</dt>
      <dd><%= upload_image.vibe %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back upload_image, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_upload_image_url(upload_image), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to upload_image, method: :delete, data: { confirm: "Do you really want to delete this upload_image?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(upload_image.updated_at) %> ago
  </div>
</div>

app/views/upload_images/_form.html.erb
<% was_validated = upload_image.errors.any? %>

<%= form_with(model: upload_image, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = upload_image.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
    <% if image_was_invalid %>
      <% upload_image.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% topstyle_class = "form-control" %>
    <% topstyle_was_invalid = upload_image.errors.include?(:topstyle) %>

    <% if was_validated %>
      <% if topstyle_was_invalid %>
        <% topstyle_class << " is-invalid" %>
      <% else %>
        <% topstyle_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :topstyle %>
    <%= f.text_field :topstyle, class: topstyle_class, placeholder: "Enter topstyle" %>
    <% if topstyle_was_invalid %>
      <% upload_image.errors.full_messages_for(:topstyle).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% topcolor_class = "form-control" %>
    <% topcolor_was_invalid = upload_image.errors.include?(:topcolor) %>

    <% if was_validated %>
      <% if topcolor_was_invalid %>
        <% topcolor_class << " is-invalid" %>
      <% else %>
        <% topcolor_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :topcolor %>
    <%= f.text_field :topcolor, class: topcolor_class, placeholder: "Enter topcolor" %>
    <% if topcolor_was_invalid %>
      <% upload_image.errors.full_messages_for(:topcolor).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% bottomstyle_class = "form-control" %>
    <% bottomstyle_was_invalid = upload_image.errors.include?(:bottomstyle) %>

    <% if was_validated %>
      <% if bottomstyle_was_invalid %>
        <% bottomstyle_class << " is-invalid" %>
      <% else %>
        <% bottomstyle_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :bottomstyle %>
    <%= f.text_field :bottomstyle, class: bottomstyle_class, placeholder: "Enter bottomstyle" %>
    <% if bottomstyle_was_invalid %>
      <% upload_image.errors.full_messages_for(:bottomstyle).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% bottomcolor_class = "form-control" %>
    <% bottomcolor_was_invalid = upload_image.errors.include?(:bottomcolor) %>

    <% if was_validated %>
      <% if bottomcolor_was_invalid %>
        <% bottomcolor_class << " is-invalid" %>
      <% else %>
        <% bottomcolor_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :bottomcolor %>
    <%= f.text_field :bottomcolor, class: bottomcolor_class, placeholder: "Enter bottomcolor" %>
    <% if bottomcolor_was_invalid %>
      <% upload_image.errors.full_messages_for(:bottomcolor).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% shoestyle_class = "form-control" %>
    <% shoestyle_was_invalid = upload_image.errors.include?(:shoestyle) %>

    <% if was_validated %>
      <% if shoestyle_was_invalid %>
        <% shoestyle_class << " is-invalid" %>
      <% else %>
        <% shoestyle_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :shoestyle %>
    <%= f.text_field :shoestyle, class: shoestyle_class, placeholder: "Enter shoestyle" %>
    <% if shoestyle_was_invalid %>
      <% upload_image.errors.full_messages_for(:shoestyle).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% shoecolor_class = "form-control" %>
    <% shoecolor_was_invalid = upload_image.errors.include?(:shoecolor) %>

    <% if was_validated %>
      <% if shoecolor_was_invalid %>
        <% shoecolor_class << " is-invalid" %>
      <% else %>
        <% shoecolor_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :shoecolor %>
    <%= f.text_field :shoecolor, class: shoecolor_class, placeholder: "Enter shoecolor" %>
    <% if shoecolor_was_invalid %>
      <% upload_image.errors.full_messages_for(:shoecolor).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% vibe_class = "form-control" %>
    <% vibe_was_invalid = upload_image.errors.include?(:vibe) %>

    <% if was_validated %>
      <% if vibe_was_invalid %>
        <% vibe_class << " is-invalid" %>
      <% else %>
        <% vibe_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :vibe %>
    <%= f.select :vibe, options_for_select(UploadImage.vibes.keys), {}, class: "form-control" %>
    <% if vibe_was_invalid %>
      <% upload_image.errors.full_messages_for(:vibe).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/upload_images/_list_item.html.erb
<%= link_to upload_image, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= upload_image %>
    <small class="text-muted">
      <%= time_ago_in_words(upload_image.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/upload_images/_upload_image_bookmarks.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Bookmarks

    <a data-toggle="collapse" href="#upload_image_bookmarks_new_form">
      Add bookmark
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @upload_image.bookmarks.each do |bookmark| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to bookmark, bookmark %>

        <%= link_to bookmark, method: :delete, data: { confirm: "Do you really want to delete this bookmark" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="upload_image_bookmarks_new_form">
        <%= render partial: "upload_images/upload_image_bookmarks_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/upload_images/_upload_image_bookmarks_new_form.html.erb
<%= form_with(model: @bookmark, local: true) do |f| %>

  <%= f.hidden_field :image_id, value: @upload_image.id %>

  <div class="form-group">
    <%= f.label :notes %>

    <%= f.text_field :notes, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create bookmark", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/upload_images/_upload_image_image_comments.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Image Comments

    <a data-toggle="collapse" href="#upload_image_image_comments_new_form">
      Add image comment
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @upload_image.image_comments.each do |image_comment| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to image_comment, image_comment %>

        <% if current_user == image_comment.commentor %>
          <%= link_to image_comment, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="upload_image_image_comments_new_form">
        <%= render partial: "upload_images/upload_image_image_comments_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/upload_images/_upload_image_image_comments_new_form.html.erb
<%= form_with(model: @image_comment, local: true) do |f| %>

  <%= f.hidden_field :image_id, value: @upload_image.id %>

  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, rows: "3", class: "form-control" %>
  </div>

  <%= f.hidden_field :commentor_id, value: current_user.id %>

  <%= f.submit "Create image comment", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/upload_images/_upload_images_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "upload_images_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :shoecolor_cont, "Shoecolor contains" %>
    <%= f.text_field :shoecolor_cont, :class => "form-control", :placeholder => "Shoecolor contains" %>
  </div>

  <div class="form-group">
    <%= f.label :shoestyle_cont, "Shoestyle contains" %>
    <%= f.text_field :shoestyle_cont, :class => "form-control", :placeholder => "Shoestyle contains" %>
  </div>

  <div class="form-group">
    <%= f.label :bottomcolor_cont, "Bottomcolor contains" %>
    <%= f.text_field :bottomcolor_cont, :class => "form-control", :placeholder => "Bottomcolor contains" %>
  </div>

  <div class="form-group">
    <%= f.label :bottomstyle_cont, "Bottomstyle contains" %>
    <%= f.text_field :bottomstyle_cont, :class => "form-control", :placeholder => "Bottomstyle contains" %>
  </div>

  <div class="form-group">
    <%= f.label :topcolor_cont, "Topcolor contains" %>
    <%= f.text_field :topcolor_cont, :class => "form-control", :placeholder => "Topcolor contains" %>
  </div>

  <div class="form-group">
    <%= f.label :topstyle_cont, "Topstyle contains" %>
    <%= f.text_field :topstyle_cont, :class => "form-control", :placeholder => "Topstyle contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/upload_images" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#upload_images_filters">
  Show filters
</a>

app/views/upload_images/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Upload Image #<%= @upload_image.id %>
      </h2>

      <div class="card-body">
        <%= render "form", upload_image: @upload_image %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/upload_images/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Upload Images

      <%= link_to new_upload_image_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "upload_images/upload_images_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Upload Images

        <%= link_to new_upload_image_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @upload_images, partial: "list_item", as: :upload_image %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @upload_images, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/upload_images/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Upload Image
      </h2>

      <div class="card-body">
        <%= render "form", upload_image: @upload_image %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/upload_images/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @upload_image, partial: "card", as: :upload_image %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "upload_images/upload_image_image_comments" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "upload_images/upload_image_bookmarks" %>
  </div>
</div>