config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :bookmarks

      resources :image_comments

      resources :upload_images

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "upload_images#index"
  resources :bookmarks
  resources :image_comments
  resources :upload_images
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/image_comment.rb
class ImageComment < ApplicationRecord
  # Direct associations

  belongs_to :image,
             class_name: "UploadImage"

  belongs_to :commentor,
             class_name: "User"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    image.to_s
  end
end

app/controllers/api/v1/image_comments_controller.rb
class Api::V1::ImageCommentsController < Api::V1::GraphitiController
  def index
    image_comments = ImageCommentResource.all(params)
    respond_with(image_comments)
  end

  def show
    image_comment = ImageCommentResource.find(params)
    respond_with(image_comment)
  end

  def create
    image_comment = ImageCommentResource.build(params)

    if image_comment.save
      render jsonapi: image_comment, status: :created
    else
      render jsonapi_errors: image_comment
    end
  end

  def update
    image_comment = ImageCommentResource.find(params)

    if image_comment.update_attributes
      render jsonapi: image_comment
    else
      render jsonapi_errors: image_comment
    end
  end

  def destroy
    image_comment = ImageCommentResource.find(params)

    if image_comment.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: image_comment
    end
  end
end

app/controllers/image_comments_controller.rb
class ImageCommentsController < ApplicationController
  before_action :current_user_must_be_image_comment_commentor,
                only: %i[edit update destroy]

  before_action :set_image_comment, only: %i[show edit update destroy]

  def index
    @q = ImageComment.ransack(params[:q])
    @image_comments = @q.result(distinct: true).includes(:commentor,
                                                         :image).page(params[:page]).per(10)
  end

  def show; end

  def new
    @image_comment = ImageComment.new
  end

  def edit; end

  def create
    @image_comment = ImageComment.new(image_comment_params)

    if @image_comment.save
      message = "ImageComment was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @image_comment, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @image_comment.update(image_comment_params)
      redirect_to @image_comment,
                  notice: "Image comment was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @image_comment.destroy
    message = "ImageComment was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to image_comments_url, notice: message
    end
  end

  private

  def current_user_must_be_image_comment_commentor
    set_image_comment
    unless current_user == @image_comment.commentor
      redirect_back fallback_location: root_path,
                    alert: "You are not authorized for that."
    end
  end

  def set_image_comment
    @image_comment = ImageComment.find(params[:id])
  end

  def image_comment_params
    params.require(:image_comment).permit(:image_id, :comment, :commentor_id)
  end
end

app/views/image_comments/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Image Comment #<%= image_comment.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Image</dt>
      <dd>
        <% if @image_comment.image.present? %>
          <%= link_to image_comment.image, image_comment.image %>
        <% end %>
      </dd>

      <dt>Comment</dt>
      <dd><%= image_comment.comment %></dd>

      <dt>Commentor</dt>
      <dd>
        <% if @image_comment.commentor.present? %>
          <%= link_to image_comment.commentor, image_comment.commentor %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back image_comment, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <% if current_user == @image_comment.commentor %>
          <%= link_to edit_image_comment_url(image_comment), class: "btn btn-block btn-sm btn-outline-secondary" do %>
            <i class="fas fa-edit"></i>
          <% end %>
        <% end %>
      </div>

      <div class="col">
        <% if current_user == @image_comment.commentor %>
          <%= link_to image_comment, method: :delete, data: { confirm: "Do you really want to delete this image_comment?" }, class: "btn btn-block btn-outline-secondary" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(image_comment.updated_at) %> ago
  </div>
</div>

app/views/image_comments/_form.html.erb
<% was_validated = image_comment.errors.any? %>

<%= form_with(model: image_comment, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% image_class = "form-control" %>
    <% image_was_invalid = image_comment.errors.include?(:image) %>

    <% if was_validated %>
      <% if image_was_invalid %>
        <% image_class << " is-invalid" %>
      <% else %>
        <% image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :image_id %>
    <%= f.collection_select :image_id, UploadImage.all, :id, :to_s, {}, class: "form-control" %>
    <% if image_was_invalid %>
      <% image_comment.errors.full_messages_for(:image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% comment_class = "form-control" %>
    <% comment_was_invalid = image_comment.errors.include?(:comment) %>

    <% if was_validated %>
      <% if comment_was_invalid %>
        <% comment_class << " is-invalid" %>
      <% else %>
        <% comment_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :comment %>
    <%= f.text_area :comment, class: comment_class, placeholder: "Enter comment" %>
    <% if comment_was_invalid %>
      <% image_comment.errors.full_messages_for(:comment).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :commentor_id, value: current_user.id %>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/image_comments/_image_comments_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "image_comments_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :comment_cont, "Comment contains" %>
    <%= f.text_field :comment_cont, :class => "form-control", :placeholder => "Comment contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :commentor_email_cont, "Commentor email contains" %>
    <%= f.text_field :commentor_email_cont, :class => "form-control", :placeholder => "Commentor email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "UploadImage Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='imagegteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :image_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "UploadImage Created at greater than or equal to", :data => {:target => '#imagegteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#imagegteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='imagelteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :image_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "UploadImage Created at less than or equal to", :data => {:target => '#imagelteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#imagelteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#imagegteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#imagelteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#imagegteqcreated_atPicker').on("dp.change", function (e) {
              $('#imagelteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#imagelteqcreated_atPicker').on("dp.change", function (e) {
              $('#imagegteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/image_comments" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#image_comments_filters">
  Show filters
</a>

app/views/image_comments/_list_item.html.erb
<%= link_to image_comment, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= image_comment %>
    <small class="text-muted">
      <%= time_ago_in_words(image_comment.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/image_comments/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Image Comment #<%= @image_comment.id %>
      </h2>

      <div class="card-body">
        <%= render "form", image_comment: @image_comment %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/image_comments/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Image Comments

      <%= link_to new_image_comment_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "image_comments/image_comments_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Image Comments

        <%= link_to new_image_comment_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @image_comments, partial: "list_item", as: :image_comment %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @image_comments, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/image_comments/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Image Comment
      </h2>

      <div class="card-body">
        <%= render "form", image_comment: @image_comment %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/image_comments/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @image_comment, partial: "card", as: :image_comment %>
  </div>
</div>